document.addEventListener("DOMContentLoaded", function(event) {
    var htmlString = `<div class="speech-row"> <div class="speech-img"><a href="127.0.0.1" target="_blank">
<img src="botoom_div2.png" width="100" height="100" alt="SJMO" ></a></div>
<div class="speech-bubble"><b>Olá, meu nome é SJMO, é assim que quero me apresentar,</b> e quero demonstrar minha tese sobre um novo conceito de transfomar energia. 
<a href="https://github.com/Sjmo1980/Energia-limpa.git" target="_blank">
<strong>Veja meus estudos e exemplos</strong></a></div></div><div class="link-row"> </div><div class="code-demo">A demonstração do projeto começa abaixo</div>
<style>.speech-row{display:flex; justify-content:center;}.link-row{margin-bottom:2rem;display:flex; justify-content:center; gap: 1rem; align-items:center;}.link-row a{text-align:center;}.speech-img{align-self: center; max-width:100%; height:auto;}.speech-img img{border-radius:50%;}.speech-bubble{max-width:300px; font-family:sans-serif; margin:1rem; padding:1rem;position: relative; border:2px solid #000;background: #fff;border-radius: .4em;}.speech-bubble:before, .speech-bubble:after{content: '';position: absolute;left: 0;top: 50%;width: 0;height: 0;border: 20px solid transparent;border-right-color: #000;border-left: 0;margin-top: -20px;margin-left: -20px;}.speech-bubble:after{border-right-color: #fff;margin-left: -18px; z-index:1;}.code-demo{text-align:center; color:#ccc;}</style>`; $(document.body).prepend(htmlString);
}); 
/*
{
    var htmlString = `<div class="speech-row"> <div class="speech-img"><a href="127.0.0.1" target="_blank"><img src="https://assets.codepen.io/172219/internal/avatars/users/default.png?format=auto&version=1643853840&width=80&height=80" alt="Jake Lett - SEO Consultant" ></a></div><div class="speech-bubble"><b>Hello, my name is Jake Lett,</b> and it's my mission to help you create or improve your website. <a href="https://www.jakelett.com/?utm_source=codepen&utm_campaign=guides&utm_medium=footer" target="_blank"><strong>View My Free Guides & Resources</strong></a></div></div><div class="link-row"> </div><div class="code-demo">Code Demo Starts Below</div><style>.speech-row{display:flex; justify-content:center;}.link-row{margin-bottom:2rem;display:flex; justify-content:center; gap: 1rem; align-items:center;}.link-row a{text-align:center;}.speech-img{align-self: center; max-width:100%; height:auto;}.speech-img img{border-radius:50%;}.speech-bubble{max-width:300px; font-family:sans-serif; margin:1rem; padding:1rem;position: relative; border:2px solid #000;background: #fff;border-radius: .4em;}.speech-bubble:before, .speech-bubble:after{content: '';position: absolute;left: 0;top: 50%;width: 0;height: 0;border: 20px solid transparent;border-right-color: #000;border-left: 0;margin-top: -20px;margin-left: -20px;}.speech-bubble:after{border-right-color: #fff;margin-left: -18px; z-index:1;}.code-demo{text-align:center; color:#ccc;}</style>`; $(document.body).prepend(htmlString);
}*/
